### PR TITLE
Getting data by dictionary's 'get' and remove not necessary catching Exception

### PR DESCRIPTION
**Pull request by touero**
This is an excellent open source project. Thanks!

While reading the source code, I found that there are parts of python that can be optimized and modified the content:
1. To obtain dict data, you can use get. When the key does not exist, you can set a default value.
2. Removed the exception that dict key does not exist.
3. Add files to gitignore that ignore the python virtual environment and the cache generated by python.

If this gets support I'll continue.

This submission has been completed. It can be merged if you want.

### CODE REVIEW

**Comment by NaiboWang** [comment]
Thank you, and this is a good function, since the function `preprocess` also has a lot of this kind of problem, maybe you or me can replace them in the future:)

**Comment by touero** [comment]
> Thank you, and this is a good function, since the function `preprocess` also has a lot of this kind of problem, maybe you or me can replace them in the future:)

`node["parameters"]` in function `preprocess`， which definitely exist?

**Comment by NaiboWang** [comment]
Yes, all Field `parameters` are stored in the `graph` field of the `.json` files in the `tasks` folder, you can open any existing tasks and check the format of the designed tasks.

**Comment by touero** [comment]
> Yes, the field `parameters` are stored in the `graph` field of the `.json` files in the `tasks` folder, you can open any existing tasks and check the format of the designed tasks.

I checked some `.json` in tasks folder random, and found only exist a key word `graph`. Why created a loop for `self.procedure`？

**Pull request merged**
